name: Maven Publish
on:
  workflow_dispatch: # This enables manual trigger
    inputs:
      newVersion:
        description: 'Set version'
        required: true
      nextVersion:
        description: 'Next version'
        required: true
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        if: ${{ success() }}

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v3.1.0
        if: ${{ success() }}
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v3.0.1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set Version from Input
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.newVersion }}
        if: github.event_name == 'workflow_dispatch'

      - name: Build and Package
        run: mvn -B package --file pom.xml
        if: ${{ success() }}

      - name: Deploy to Local Repo
        run: mvn deploy
        if: ${{ success() }}
        if: github.event_name == 'workflow_dispatch'

      - name: Set Next Version from Input
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.nextVersion }}
        if: ${{ success() }}
        if: github.event_name == 'workflow_dispatch'

      - name: Checkout Maven Repo
        uses: actions/checkout@v2
        if: ${{ success() }}
        if: github.event_name == 'workflow_dispatch'
        with:
          repository: raisercostin/maven-repo
          path: maven-repo

      - name: Copy Artifacts
        run: cp -R target/maven-repo/* maven-repo/
        if: ${{ success() }}
        if: github.event_name == 'workflow_dispatch'

      - name: Push to GitHub Maven Repo
        run: |
          cd maven-repo
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Publish Maven Artifacts"
          git push
        if: ${{ success() }}
        if: github.event_name == 'workflow_dispatch'
